# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: check-toml
    -   id: check-case-conflict
    -   id: check-builtin-literals
    -   id: check-ast
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.1'
    hooks:
    -   id: isort
        additional_dependencies: ["toml"]
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
