schedule_tables_to_scrape:
#  - [2019, "October"]
#  - [2019, "November"]
#  - [2019, "December"]
#  - [2019, "January"]
#  - [2019, "February"]
#  - [2019, "March"]
#  - [2019, "April"]
#  - [2019, "May"]
  - [2020, "October"]
  - [2020, "November"]
  - [2020, "December"]